services:
  - type: web
    name: shadowtrace
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py app:app
    envVars:
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASS
        sync: false
      - key: ADMIN_SECRET_KEY
        sync: false
      - key: ADMIN_PREFIX
        sync: false
